name: teslo_shop
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: "^3.5.1"

dependencies:
  dio: ^5.7.0
  envied: ^1.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  formz: ^0.8.0
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  logger: ^2.5.0
  shared_preferences: ^2.3.4

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  envied_generator: ^1.0.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true

  assets:
    - assets/loaders/
    - assets/images/
    - google_fonts/montserrat_alternates/
